### ISSUE TITLE
Gold recording error

### ISSUE THREAD

**Issue by 1532114861** [will0w7/MoneyLooter#14]
I'm playing the Wrath of the Lich King version, and sometimes the recorded gold from dungeons shows as much higher than it actually is.
![Snipaste_2024-10-11_11-48-35](https://github.com/user-attachments/assets/735b8e55-1337-421e-b211-cf89efee5268)

**Comment by will0w7** [comment]
Hi! I'm sorry to hear that.

Since the official WOTLK servers are no longer available, it's not possible to provide support for these versions. MoneyLooter is only compatible with the **official servers**.

You can check compatibility here: [Compatibility Status](https://github.com/will0w7/MoneyLooter?tab=readme-ov-file#compatibility-status)
