### ISSUE TITLE
showing 0 copper

### ISSUE THREAD

**Issue by drxnaren** [will0w7/MoneyLooter#15]
My "items" and "priciest" values are just showing 0 copper. https://prnt.sc/snUX9gokc8jV

**Comment by will0w7** [comment]
Hi! Can you add some information to help me find the error?

1. What version of the game are you playing? It is important to note that only official versions of the game are supported.
2. What language do you play the game in? It seems that you are playing in English.
3. Do you have any Lua errors? If you use BugSack and BugGrabber you should have a button on the minimap that lists the errors.

Thanks for the report :)

**Comment by drxnaren** [comment]
I'm on the official Classic Era (not SoD). It is indeed in English, and i downloaded bugsack and it does not display any Lua errors related to MoneyLooter.

Here is a screenshot of the tooltip when hovering over bugsack button: https://prnt.sc/h7CwMvjTG5G_

**Comment by will0w7** [comment]
Hi again!

It seems like you have a lot of buggy addons, which could cause multiple things to fail in the UI.
You have 2 options: update the addons or remove them.

From the screenshot you sent, I can see several buggy addons:
Spy: [https://www.curseforge.com/wow/addons/spy](https://www.curseforge.com/wow/addons/spy)
FormatFix: [https://www.curseforge.com/wow/addons/formatfix](https://www.curseforge.com/wow/addons/formatfix)
Delete Cheapest Item: [https://www.curseforge.com/wow/addons/delete-cheapest-item](https://www.curseforge.com/wow/addons/delete-cheapest-item)
Wowhead Looter: This addon is installed by Wowhead Client to monitor loot and send the information to Wowhead (this is how they can give approximate loot percentages) [https://www.wowhead.com/client](https://www.wowhead.com/client)

Seeing the amount of errors you have, it's possible that you have even more that can't be seen in the screenshot. I recommend you to delete all the addons you don't use or update them.

MoneyLooter doesn't necessarily have to be crashing, but bugs from other addons can prevent it from working properly. From the description of the bug you've given, it seems that the Wowhead Looter addon is breaking MoneyLooter's functionality by crashing. But this is just a guess, you'd have to get rid of all the bugs by updating the addons or just deleting them before you know if that's the source of the problem.
You should also check if you have any old WeakAuras that you're not using that could be causing problems.

I've been testing MoneyLooter in Classic Era this morning and it works fine with all types of loot, I'm 99% sure that the problem is coming from the broken addons.

Good luck! If you manage to resolve the problem with MoneyLooter this way or the problem persists, please let me know :)
